### PR TITLE
Describe pg_service

### PR DESCRIPTION
**Pull request by PeterPetrik**
please note this is just a draft/my notes about how to use it. @alex-cit feel free to finish it / rewrite after the functionality is in master 

see https://github.com/MerginMaps/mobile/pull/2913

### CODE REVIEW

**Comment by rastermanden** [comment]
We have tested this and it works! Thank you

**Comment by alex-cit** [comment]
@PeterPetrik thanks for the draft, I made some small changes, please check if it still makes sense :)

**Comment by PeterPetrik** [comment]
all nice, thanks

**Comment by PeterPetrik** [comment]
I am wondering if we shouldn't add th

**Pull request merged**
