### PR TITLE
add banner for non-english versions

### PR DESCRIPTION
**Pull request by PeterPetrik**
We want to try to use Weglot for machine translations of the docs, we place small text for language mutations (e.g. on `de.merginmaps.com/docs`

fix https://github.com/MerginMaps/docs/issues/133

Screenshot 2023-11-02 at 16 31 02

cc @janpaulovic1 @mostlyAtNight

### CODE REVIEW

**Comment by MarcelGeo** [comment]
I added targeting window object into mounted lifecycle method, which is called after append to DOM. Build is successfull on my machine . @PeterPetrik can you verify it?

**Comment by PeterPetrik** [comment]
@MarcelGeo it is good, I have created new Weglot project for docs, they said we should insert this code before `<head>` tag, do you know how to do it?

```
<script type="text/javascript" src="https://cdn.weglot.com/weglot.min.js"></script>
<script>
    Weglot.initialize({
        api_key: 'wg_793fda6a46586055f8d5df5cc9fa6a270',
        hide_switcher: true
    });
</script>
```

**Comment by MarcelGeo** [comment]
> @MarcelGeo it is good, I have created new Weglot project for docs, they said we should insert this code before `<head>` tag, do you know how to do it?
> 
> ```
> <script type="text/javascript" src="https://cdn.weglot.com/weglot.min.js"></script>
> <script>
>     Weglot.initialize({
>         api_key: 'wg_793fda6a46586055f8d5df5cc9fa6a270',
>         hide_switcher: true
>     });
> </script>
> ```
> 
>     * also we may want to add dev.merginmaps.com to the list of hostnames without banner
> 
> 
> For general approach I suggest (at least for beginning until we verify the quality of AI translations) 1/ on marketing web merginmaps.com we will have in menu link to ENGLISH version of docs (from ALL languages) 2/ on merginmaps.com/docs ENGLISH version, we will not have language switcher at all 3/ on .merginmaps.com/docs we will have banner that this is machine translated with link to ENGLISH version of the docs.

Do we want to display switcher in dev mode? @PeterPetrik

**Comment by PeterPetrik** [comment]
> Do we want to display switcher in dev mode? @PeterPetrik

@MarcelGeo no, I want to just show banner in sidebar on production and non-english version. In english version I do **not** want to show switcher anywhere.

**Comment by PeterPetrik** [comment]
There is a problem on Weglot side - I have reverted this

**Pull request merged**
