### PR TITLE
Rebranding

### PR DESCRIPTION
**Pull request by PeterPetrik**
TODO: 
- favicon (bigger?)
- merginmaps logo in link (http://localhost:8080/docs/misc/write-docs/#reference-mergin-project)
- merginmaps logo in header (bigger? as text?)
- font color - black or our black?

Screenshot 2022-04-25 at 10 49 07

### CODE REVIEW

**Comment by tomasMizera** [comment]
Icons/logos are now replaced with no or lower padding

**Header:**. 
merginmaps Documentation

**Mergin maps project ref:**
Pasted Graphic 4

**Mergin maps project ref short**
Pasted Graphic 5

What do you think @PeterPetrik ?

**Comment by PeterPetrik** [comment]
whatabout favicon?

**Comment by PeterPetrik** [comment]
also is it possible to use "documentation" with lowercase "D" in header?

**Review by tomasMizera — APPROVED** [review]

**Comment by tomasMizera** [comment]
New favicon: 
image

**Comment by tomasMizera** [comment]
We are ready for release 🥳

**Pull request merged**
